<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>

<head>
<title>write example</title>

<script type="text/javascript">


/* 
Each new term in the Fibonacci sequence isgenerated by adding
the previous two terms. By starting with 1 and 2, 
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values
do not exceed four million, find the sum of the even-valued terms. 
*/



function fibonacci(n) {
   if (n < 2){
     return 1;
   }else{
     return fibonacci(n-2) + fibonacci(n-1);
   }
}
var answer = 0;
var arr = [];
var j = 0;
while (fibonacci(j) <15) {
    var value = 0;
    value += fibonacci(j);
    if(value % 2 === 0) {
        arr.push(value);
        answer += value;
    }
     var termValue = j ;
    j++;
}
console.log("the term value is: " + termValue)
console.log("The set of even fibanacci numbers is: " + arr);
console.log("The sum of the even fibonacci numbers is " + answer);



</script>
</head>

<body>

</body>
</html>


<!-- 
Debrief thoughts:  
A quicker way that did not require a recursive function, 
however, I wanted to explore the programming more than just solving a math program.

Seeing that a recursive function can be viewed as three repeating values 
where every third term beggining at the second term is even(b).  (a, 2, c, a, 8, c, a, 34, c, a, even(b), c ...) 

a=1;
b=2; //this is always the even term
c=3;

while (b< 4000000) {
b += b;
a= b + c;
b= c + a;
c= a + b;
}
-->